# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

# Environment YAML files can be used to supplement
# the variables specified in 'config/variables/common.yml'. You can:
#   * Override existing common-vars.yml variable value settings, and
#   * Create new variable values not present in common-vars.yml
#
# The naming convention for these YAML files is:
#   {organization}-{branch}.yml
#
# where {organization} is the organization variable from the
#         common.yml file
# and   {branch} is the Azure Repos branch name used by the
#         currently executing pipeline.

variables:
  deploymentRegion: canadacentral

  # Management Groups
  var-managementgroup-hierarchy: >
    {
      "name": "Tenant Root Group",
      "id": "c0156602-5e7d-47be-9128-69dbf7152c17",
      "children": [
        {
          "name": "Azure Landing Zones",
          "id": "ALZ",
          "children": [
            {
              "name": "Platform", "id": "Platform",
              "children": [
                { "name": "Identity", "id": "Identity", "children": [] },
                { "name": "Connectivity", "id": "Connectivity", "children": [] },
                { "name": "Management", "id": "Management", "children": [] }
              ]
            },
            {
              "name": "Landing Zones", "id": "LandingZones",
              "children": [
                { "name": "Production", "id": "Production", "children": [] },
                { "name": "Non-Production", "id": "NonProduction", "children": [] }
              ]
            },
            {
              "name": "Sandbox", "id": "Sandbox",
              "children": []
            }
          ]
        }
      ]
    }

  # Logging
  var-logging-region: canadacentral
  var-logging-managementGroupId: Management
  var-logging-subscriptionId: 640251f9-f1ee-4b33-93ee-d49a8e8347d4
  var-logging-configurationFileName: logging.parameters.json

  ## This parameter is only used for HIPAA/HITRUST Policy Assignment
  var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: alznsg

  # Hub Networking
  var-hubnetwork-region: canadacentral
  var-hubnetwork-managementGroupId: Connectivity
  var-hubnetwork-subscriptionId: 49f510ff-d019-47c4-b2dd-d6781b4b6d7b

  ## Hub Network configuration using Azure Firewall - required when Azure Firewall is used
  var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json

  ## Hub Network configuration using Network Virtual Appliance (NVA) - required when Network Virtual Appliance (NVA) like Fortigate Firewalls are used
  var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json