variables:
  var-logging-region: canadacentral
  var-identity-configurationFileName: identity.parameters.json
  var-hubnetwork-region: canadacentral
  var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-hubnetwork-managementGroupId: Connectivity
  var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  var-managementgroup-hierarchy: |-
    {
      "name": "Tenant Root Group",
      "children": [
        {
          "name": "Canadian Public Sector Azure Landing Zones",
          "children": [
            {
              "name": "Platform",
              "children": [
                {
                  "name": "Management",
                  "children": [],
                  "id": "Management"
                },
                {
                  "name": "Connectivity",
                  "children": [],
                  "id": "Connectivity"
                },
                {
                  "name": "Identity",
                  "children": [],
                  "id": "Identity"
                }
              ],
              "id": "Platform"
            },
            {
              "name": "LandingZones",
              "children": [
                {
                  "name": "NonProd",
                  "children": [],
                  "id": "NonProd"
                },
                {
                  "name": "Prod",
                  "children": [],
                  "id": "Prod"
                }
              ],
              "id": "LandingZones"
            },
            {
              "name": "Sandbox",
              "children": [],
              "id": "Sandbox"
            }
          ],
          "id": "pubsec"
        }
      ],
      "id": "df968f64-5f44-4e42-937b-47fb792ee373"
    }
  var-logging-subscriptionId: 328571fc-539a-4d92-b181-17d14b6fe75c
  var-logging-managementGroupId: Management
  var-logging-configurationFileName: logging.parameters.json
  var-identity-managementGroupId: Identity
  var-identity-subscriptionId: 4436ceeb-dcd9-4463-82fb-37a05ba77b77
  var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  var-identity-region: canadacentral
  deploymentRegion: canadacentral
  var-hubnetwork-subscriptionId: 9e917d2d-f13a-4cc9-ba38-1ecc255a8c81

