variables:
  var-hubnetwork-region: canadacentral
  var-hubnetwork-managementGroupId: Connectivity
  var-hubnetwork-azfw-configurationFileName: hub-azfw/hub-network.parameters.json
  var-hubnetwork-nva-configurationFileName: hub-nva/hub-network.parameters.json
  var-hubnetwork-subscriptionId: a0c1a4a0-74bc-422b-8e8d-71f1d016e69d
  var-hubnetwork-azfwPolicy-configurationFileName: hub-azfw-policy/azure-firewall-policy.parameters.json
  var-logging-managementGroupId: Management
  var-logging-subscriptionId: 8dda93c7-1801-480d-a82a-2620875371fa
  deploymentRegion: canadacentral
  var-identity-managementGroupId: Identity
  var-logging-diagnosticSettingsforNetworkSecurityGroupsStoragePrefix: pubsecnsg
  var-logging-configurationFileName: logging.parameters.json
  var-managementgroup-hierarchy: |-
    {
      "id": "61e54fa4-fa93-43b3-9775-a60c5495ffdc",
      "name": "Tenant Root Group",
      "children": [
        {
          "id": "pubsec",
          "name": "Canadian Public Sector Azure Landing Zones",
          "children": [
            {
              "id": "Platform",
              "name": "Platform",
              "children": [
                {
                  "id": "Management",
                  "name": "Management",
                  "children": []
                },
                {
                  "id": "Connectivity",
                  "name": "Connectivity",
                  "children": []
                },
                {
                  "id": "Identity",
                  "name": "Identity",
                  "children": []
                }
              ]
            },
            {
              "id": "LandingZones",
              "name": "LandingZones",
              "children": [
                {
                  "id": "DevTest",
                  "name": "DevTest",
                  "children": []
                },
                {
                  "id": "QA",
                  "name": "QA",
                  "children": []
                },
                {
                  "id": "Prod",
                  "name": "Prod",
                  "children": []
                }
              ]
            },
            {
              "id": "Sandbox",
              "name": "Sandbox",
              "children": []
            }
          ]
        }
      ]
    }
  var-logging-region: canadacentral
  var-identity-configurationFileName: identity.parameters.json
  var-identity-region: canadacentral
  var-identity-subscriptionId: 7281b8be-c687-468b-9519-a8e6b28f66c9

