# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

parameters:
  - name: subscriptionGuid
    type: string
  - name: subscriptionType
    type: string
  - name: subscriptionLocation
    type: string
  - name: filename
    type: string
  - name: workingDir
    type: string

steps:

- task: PowerShell@2
  displayName: Validate Archetype Parameters
  inputs:
    targetType: 'inline'
    script: |
      $schemaFile="$(Build.SourcesDirectory)/schemas/latest/landingzones/lz-${{ parameters.subscriptionType}}.json"
      $parameterFile="${{ parameters.workingDir }}/${{ parameters.filename }}"

      Write-Host "Parameters File: ${parameterFile}"
      Write-Host "Schema File: ${schemaFile}"

      Get-Content -Raw "${parameterFile}" | Test-Json -SchemaFile "${schemaFile}"
  
- task: AzureCLI@2
  displayName: Deploy Archetype
  inputs:
    azureSubscription: $(serviceConnection)
    workingDirectory: '${{ parameters.workingDir }}'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $(var-bashPreInjectScript)

      template="landingzones/lz-${{ parameters.subscriptionType}}/main.bicep"
      deployName='main-${{ parameters.subscriptionGuid }}-${{ parameters.subscriptionLocation }}'
      deployName=${deployName:0:63}

      echo "Configuring subscription ${{ parameters.subscriptionGuid }} using template ${template} ..."

      # Check if the log analytics workspace id is provided in the parameters json.
      # If present, then do no change it.  Otherwise add it to the json parameter file.
      LOG_ANALYTICS_WORKSPACE_RESOURCE_ID_IN_PARAMETERS=`jq -r .parameters.logAnalyticsWorkspaceResourceId.value ${{ parameters.filename }}`   

      if [[ $LOG_ANALYTICS_WORKSPACE_RESOURCE_ID_IN_PARAMETERS != null && "$LOG_ANALYTICS_WORKSPACE_RESOURCE_ID_IN_PARAMETERS" != "" ]];
      then
        echo "Log Analytics Workspace Resource ID is set in ${{ parameters.filename }} to $LOG_ANALYTICS_WORKSPACE_RESOURCE_ID_IN_PARAMETERS"
      else
        echo "Log Analytics Workspace Resource ID is not set in ${{ parameters.filename }}.  Updating ${{ parameters.filename }} with $(var-logging-logAnalyticsWorkspaceResourceId)"

        # use jq to update the json parameter file
        echo "$( jq '.parameters.logAnalyticsWorkspaceResourceId.value = "$(var-logging-logAnalyticsWorkspaceResourceId)"' ${{ parameters.filename }} )" > ${{ parameters.filename }}
      fi

      az deployment sub $(deployOperation) \
        --subscription ${{ parameters.subscriptionGuid }} \
        --location ${{ parameters.subscriptionLocation }} \
        --template-file $(Build.SourcesDirectory)/${template} \
        --name ${deployName} \
        --parameters @${{ parameters.filename }}

      $(var-bashPostInjectScript)
