# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

trigger: none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #     - landingzones/lz-platform-connectivity-hub-azfw
  #     - .pipelines/platform-connectivity-hub-azfw.yml  
  #     - .pipelines/templates/steps/deploy-platform-connectivity-hub-azfw.yml

pr: none

variables:
- name: devops-org-name
  value: ${{ replace(replace(variables['System.CollectionUri'], 'https://dev.azure.com/' , ''), '/', '') }}
- name: logging-config-directory
  value: $(System.DefaultWorkingDirectory)/$(loggingPathFromRoot)/${{ variables['devops-org-name'] }}-${{ variables['Build.SourceBranchName'] }}
- name: networking-config-directory
  value: $(System.DefaultWorkingDirectory)/$(networkPathFromRoot)/${{ variables['devops-org-name'] }}-${{ variables['Build.SourceBranchName'] }}
- name: variable-template-file
  value: ${{ variables['devops-org-name'] }}-${{ variables['Build.SourceBranchName'] }}.yml
- template: ../config/variables/common.yml
- template: ../config/variables/${{ variables['variable-template-file'] }}

pool:
  vmImage: $[ variables.vmImage ]
  
stages:

- stage: DeployNetworkingStage
  displayName: Deploy Networking Stage

  jobs:

  - deployment: DeployNetworkingJob
    displayName: Deploy Networking Job
    environment: ${{ variables['Build.SourceBranchName'] }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - template: templates/steps/load-variables.yml

          - template: templates/steps/load-log-analytics-vars.yml
            parameters:
              logAnalyticsSubscriptionId: $(var-logging-subscriptionId)
              logAnalyticsConfigurationFile: ${{ variables['logging-config-directory'] }}/$(var-logging-configurationFileName)

          - template: templates/steps/show-variables.yml
            parameters:
              json: ${{ convertToJson(variables) }}

          - template: templates/steps/deploy-platform-connectivity-hub-azfw.yml
            parameters:
              workingDir: $(System.DefaultWorkingDirectory)/landingzones
              deployOperation: ${{ variables['deployOperation'] }}
              networkingManagementGroupId: $(var-hubnetwork-managementGroupId)
              networkingSubscriptionId: $(var-hubnetwork-subscriptionId)
              networkingRegion: $(var-hubnetwork-region)
              networkingConfigurationPath: ${{ variables['networking-config-directory'] }}/$(var-hubnetwork-azfw-configurationFileName)
              azureFirewallPolicyConfigurationPath: ${{ variables['networking-config-directory'] }}/$(var-hubnetwork-azfwPolicy-configurationFileName)

