# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 1 - Management Groups

on:
  workflow_dispatch:
    inputs:
      environmentName:
        type: string
        description: Environment name (optional), e.g. CanadaESLZ-main
        required: false

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:
  management-groups:
    name: Management Groups
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module powershell-yaml -Force

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureCloud'
        enable-AzPSSession: true
        allow-no-subscriptions: true

    - name: Deploy Management Groups
      uses: azure/powershell@v1
      with:
          inlineScript: |
            ./RunWorkflows.ps1 `
              -DeployManagementGroups `
              -EnvironmentName '${{github.event.inputs.environmentName}}' `
              -GitHubRepo ${env:GITHUB_REPOSITORY} `
              -GitHubRef ${env:GITHUB_REF}
          azPSVersion: "latest"