# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 5 - Hub Network with Azure Firewall

on: workflow_dispatch

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:
  management-groups:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Required modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy Hub Network with Azure Firewall
      run: |
        ./RunWorkflows.ps1 `
          -DeployHubNetworkWithAzureFirewall `
          -LoginServicePrincipalJson '${{secrets.AZURE_CREDENTIALS}}' `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}
