# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 6 - Subscriptions

on:
  workflow_dispatch:
    inputs:
      subscriptionIds:
        type: string
        description: Subscription ID(s)
        required: false
      environmentName:
        type: string
        description: Environment name
        required: false

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:
  subscriptions:
    name: Subscriptions
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Required modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy Subscriptions
      if: github.event.inputs.subscriptionIds != null
      run: |
        ./RunWorkflows.ps1 `
          -DeploySubscriptionIds @( ${{github.event.inputs.subscriptionIds}} ) `
          -EnvironmentName @( ${{github.event.inputs.environmentName}} ) `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.ALZ_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}
