name: Management Groups

on: workflow_dispatch

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:
  management-groups:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Required modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force

    - name: Deploy Management Groups
      run: |
        . ./RunWorkflows.ps1 `
          -DeployManagementGroups ``
          -LoginServicePrincipalJson '${{secrets.AZURE_CREDENTIALS}}' `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}
