name: Management Groups

on: workflow_dispatch

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

# https://docs.microsoft.com/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-a-service-principal-secret
# https://github.com/marketplace/actions/azure-login
# https://github.com/azure/powershell

jobs:
  management-groups:
    runs-on: ubuntu-latest
    steps:

    - name: Login   # https://github.com/Azure/login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
        allow-no-subscriptions: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Test
      run: |
        Get-Location

    - name: Install prerequisites
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Get-Location
          .\Install-Prerequisites.ps1
        azPSVersion: "latest"

    - name: Show Variables step
      run: |
        Write-Output "Repo:   ${env:GITHUB_REPOSITORY}"
        Write-Output "Branch: ${env:GITHUB_REF}"
