name: Management Groups

on: workflow_dispatch

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:
  management-groups:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install required modules
      run: |
        Get-Location
        Install-Module powershell-yaml -Force

    - name: Login
      run: |
        Get-Location
        RunWorkflows.ps1 `
          -LoginServicePrincipalJson @"
          ${{secrets.AZURE_CREDENTIALS}}
          "@

    - name: Show Variables
      run: |
        Write-Output "Repo:   ${env:GITHUB_REPOSITORY}"
        Write-Output "Branch: ${env:GITHUB_REF}"
