name: Show Variables workflow

on: workflow_dispatch

defaults:
  run:
    shell: pwsh
    working-directory: scripts/deployments

jobs:
  show-vars:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Show Variables step
      run: |
        Write-Output "${env}"
